### ISSUE TITLE
Differed description with clickhouse doc for clickhouse copier

### ISSUE THREAD

**Issue by cangyin** [Altinity/altinityknowledgebase#60]
https://github.com/Altinity/altinityknowledgebase/blob/f24f1b183b15e3d1b8856145084ffc2184713978/content/en/altinity-kb-setup-and-maintenance/altinity-kb-data-migration/_index.md?plain=1#L59

but clickhouse [doc](https://clickhouse.com/docs/en/operations/utilities/clickhouse-copier#:~:text=To%20reduce%20network%20traffic%2C%20we%20recommend%20running%20clickhouse%2Dcopier%20on%20the%20same%20server%20where%20the%20source%20data%20is%20located.) says (emphasis on me):

```
To reduce network traffic, we recommend running clickhouse-copier on the same server where the **source** data is located.
```

**Comment by SaltTan** [comment]
It depends on the configuration of your clusters.
Copier selects from the source cluster and inserts into the target cluster.
If you insert from one shard into several it is better to run copier on the source.
If you insert from several shards into one it is better to run copier on the target.
Otherwise it doesn't matter much.

**Comment by cangyin** [comment]
Thanks, that's much clearer!
